server: 
  port: 8090
logging:
  config: classpath:logback-spring.xml
  file: server.log
  path: /log/
spring:
    mvc: 
    #出现错误时, 直接抛出异常
      throw-exception-if-no-handler-found: true
    resources: 
    #不要为我们工程中的资源文件建立映射
      add-mappings: false  
    thymeleaf: 
      mode: HTML
      content-type: text/html
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.106.22.160:3306/mayday
        username: mayday
        password: mayday123456
        driver-class-name: com.mysql.jdbc.Driver
mybatis: 
  typeAliasesPackage: com.songhaozhi.mayday.model.domain
  mapperLocations: classpath:mapper/*.xml
